//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class car
    {
        public int IdCar { get; set; }
        public string marque { get; set; }
        public Nullable<double> kilometrage { get; set; }
        public Nullable<double> prix { get; set; }
        public string idClient { get; set; }
        [DisplayName("image")]

        public string photo { get; set; }
        public virtual client client { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        internal object ToList()
        {
            throw new NotImplementedException();
        }
    }
}
