//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Offre
    {
        public int IdOffre { get; set; }
        public Nullable<double> kilometrage { get; set; }
        public string marque { get; set; }
        public Nullable<double> prix { get; set; }
        public string photo { get; set; }
        public string idClient { get; set; }
    
        public virtual client client { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

    }
}
